//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMotionServices.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BMotionDBEntities : DbContext
    {
        public BMotionDBEntities()
            : base("name=BMotionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Fuel> Fuels { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Outlet> Outlets { get; set; }
        public virtual DbSet<Restriction> Restrictions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<sp_HistorPerUser_Result> sp_HistorPerUser(string nip)
        {
            var nipParameter = nip != null ?
                new ObjectParameter("nip", nip) :
                new ObjectParameter("nip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_HistorPerUser_Result>("sp_HistorPerUser", nipParameter);
        }
    
        public virtual ObjectResult<string> sp_UserPurchasedBBM(string nip)
        {
            var nipParameter = nip != null ?
                new ObjectParameter("nip", nip) :
                new ObjectParameter("nip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_UserPurchasedBBM", nipParameter);
        }
    
        public virtual ObjectResult<string> sp_UserQuota(string nip)
        {
            var nipParameter = nip != null ?
                new ObjectParameter("nip", nip) :
                new ObjectParameter("nip", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_UserQuota", nipParameter);
        }
    }
}
