//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMotionServices.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public string DocumentNo { get; set; }
        public string NIP { get; set; }
        public string DocumentFile { get; set; }
        public Nullable<int> Quota { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string IsVerify { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual User User { get; set; }
    }
}
